services:
  db: # PostgreSQL database service
    image: postgres:16-alpine
    container_name: sapient_unefa_db
    environment: # Environment variables for PostgreSQL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    healthcheck: # Health check for the database service
      test: ["CMD-SHELL", "pg_isready -U postgresql -d sapient_unefa"]
      interval: 5s
      timeout: 5s
      retries: 5
  django:
    build: .
    container_name: sapient_unefa_app
    ports:
      - "8000:8000"
    environment: # Environment variables for the web service
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL
      - SECRET_KEY
      - DEEPSEEK_API_KEY
      - CONTAINERIZED=true
    volumes:
      - .:/app
    depends_on: # Ensuring the web service starts after the database is healthy
      db:
        condition: service_healthy
  nginx:
    build: ./server
    container_name: sapient_unefa_media
    ports:
      - "80:80"
    volumes:
      - ./app/media:/app/media # Share volume with the backend web service
