version: "3.9"
services:
  application:
    build:
      context: .
      dockerfile: dockerfile.dev
    environment:
      - DEEPSEEK_API_KEY
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
